openapi: 3.0.0
info:
  version: 1.0.0
  title: Morellis Flavor Notifications API
  termsOfService: 'https://example.com/terms/'
  contact:
    email: jcorry@gmail.com
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://apis.guru/openapi-template/logo.png'
  description: >
    A notifications API for informing customers when their favorite ice cream flavor is available at Morellis Gourmet Ice Cream, the best ice cream shop in Atlanta!
externalDocs:
  description: Find out how to create Github repo for your OpenAPI spec.
  url: 'https://github.com/Rebilly/generator-openapi-repo'
tags:
  - name: Auth
    description: |
      Authentication endpoint.
  - name: Flavor
    description: |
      Flavors are ice cream flavors. Endpoints include simple CRUD operations.
  - name: Ingredient
    description: |-
      Ingredients are a property of Flavors but exist as a separate endpoint so that they can be searched
      and retrieved to make the Ingredient->User association used to determine which Users should be
      notified when Flavors are updated.
  - name: User
    description: |
      User management endpoints allow a user to manage themselves or an admin level user to manage any other user.
  - name: Store
    description: |
      Store management endpoints allow a user to manage Store location data.
paths:
  /auth:
    $ref: "./paths/auth.yaml"
  /user:
    $ref: "./paths/user.yaml"
  /user@id:
    $ref: "./paths/user@{id}.yaml"
  /user@userId@ingredient:
    $ref: "./paths/user@{userId}@ingredient.yaml"
  /user@userId@ingredient@userIngredientId:
    $ref: "./paths/user@{userId}@ingredient@{userIngredientId}.yaml"
  /user@userId@permission.yaml:
    $ref: "./paths/user@{userId}@permission.yaml"
  /store:
    $ref: "./paths/store.yaml"
  /store@{id}:
    $ref: "./paths/store@{id}.yaml"
  /flavor:
    $ref: "./paths/flavor.yaml"
  /flavor@{id}:
    $ref: "./paths/flavor@{id}.yaml"
components:
  schemas:
    User:
      $ref: "./components/schemas/User.yaml"
    ListMeta:
      $ref: "./components/schemas/ListMeta.yaml"
    UserIngredient:
      $ref: "./components/schemas/UserIngredient.yaml"
    Store:
      $ref: "./components/schemas/Store.yaml"
    Flavor:
      $ref: "./components/schemas/Flavor.yaml"
    Ingredient:
      $ref: "./components/schemas/Ingredient.yaml"
servers:
  - url: 'http://localhost:4001/api/v1'
